[tool.black]
line-length = 119
target-version = ['py38']

[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = ["C901"]
select = ["C", "E", "F", "I", "W"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["jat"]
