python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-assembly --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-basketball --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-bin-picking --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-box-close --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-button-press-topdown-wall --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-button-press-topdown --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-button-press-wall --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-button-press --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-coffee-button --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-coffee-pull --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-coffee-push --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-dial-turn --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-disassemble --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-door-close --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-door-lock --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-door-open --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-door-unlock --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-drawer-close --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-drawer-open --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-faucet-close --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-faucet-open --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-hammer --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-hand-insert --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-handle-press-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-handle-press --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-handle-pull-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-handle-pull --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-lever-pull --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-peg-insert-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-peg-unplug-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-pick-out-of-hole --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-pick-place-wall --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-pick-place --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-plate-slide-back-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-plate-slide-back --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-plate-slide-side --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-plate-slide --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-push-back --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-push-wall --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-push --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-reach-wall --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-reach --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-shelf-place --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-soccer --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-stick-pull --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-stick-push --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-sweep-into --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-sweep --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-window-close --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks metaworld-window-open --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-ant --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-doublependulum --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-halfcheetah --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-hopper --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-humanoid --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-pendulum --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-pusher --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-reacher --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-standup --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-swimmer --trust_remote_code --num_episodes 10 --save_video
python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks mujoco-walker --trust_remote_code --num_episodes 10 --save_video