name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: {}

jobs:
  run-tests-ubuntu:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MuJoCo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libosmesa6-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev,test]'
    - name: Check quality
      run: |
        make quality
    - name: Run tests
      run: |
        make test

