name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda env & dependencies
      run: |
       conda install python=${{ matrix.python-version }}
       pip install -e '.[dev,test]'
       conda list
    - name: Check quality
      run: |
        make quality
    - name: Download the imitation learning test datasets
      run: |
        chmod +x scripts/download_all_test_datasets.sh
        chmod +x scripts/download_mujoco_datasets.sh
        ./scripts/download_all_test_datasets.sh

    - name: Run tests
      run: |
        make test

