name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MuJoCo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglfw3 curl libglew-dev net-tools vim wget xpra xserver-xorg-dev build-essential libssl-dev libffi-dev libxml2-dev  libxslt1-dev zlib1g-dev libglu1-mesa-dev libgl1-mesa-dev libosmesa6-dev xvfb unzip patchelf ffmpeg cmake swig git
        python -m pip install --upgrade pip
    - name: Update path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Additional step for MuJoCo installation
      run: |
        url="https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz"
        target_folder=~/.mujoco
        mkdir -p "$target_folder"
        tar_filename="$target_folder/$(basename "$url")"
        curl -o "$tar_filename" "$url"
        tar -xzf "$tar_filename" -C "$target_folder"
        rm "$tar_filename"
        echo "LD_LIBRARY_PATH=$HOME/.mujoco/mujoco210/bin:/usr/lib:/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Install env & dependencies
      run: |
        python --version
        python -m pip install free-mujoco-py==2.1.6
        python -m pip install -e '.[dev,test]'
    - name: Check quality
      run: |
        make quality
    - name: Run tests
      run: |
        make test

