name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MuJoCo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libosmesa6-dev libgl1-mesa-glx
    - name: Update path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Additional step for MuJoCo installation
      run: |
        url="https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz"
        target_folder=~/.mujoco
        mkdir -p "$target_folder"
        tar_filename="$target_folder/$(basename "$url")"
        curl -o "$tar_filename" "$url"
        tar -xzf "$tar_filename" -C "$target_folder"
        rm "$tar_filename"
        echo "LD_LIBRARY_PATH=$HOME/.mujoco/mujoco210/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Install conda env & dependencies
      run: |
        conda install python=${{ matrix.python-version }}
        conda install libgcc
        strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
        pip install -e '.[dev,test]'
        conda list
    - name: Check quality
      run: |
        make quality
    - name: Run tests
      run: |
        make test

